a = input('첫 번째 소숫점 숫자를 입력하세요 : ')
float_a = float(a)
int_a = int(float_a)
b = input('두 번째 소숫점 숫자를 입력하세요 : ')
float_b = float(b)
int_b = int(float_b)
print()
print('정수 계산값 :',int_a + int_b)
print('실수 계산값 :',float_a + float_b)
