print('[단! 한방에! 사칙연상해주는 미니계산기!]')
print('a _ b = ???')
print()
a = input('a항을 입력하세요 : ')
int_a = int(a)
b = input('b항을 입력하세요 : ')
int_b = int(b)
print()
print('계산중입니다...')
print()
print('1. 덧셈 :',int_a + int_b)
print('2. 뺄셈 :',int_a - int_b)
print('3. 곱셈 :',int_a * int_b)
print('4. 나눗셈 :',int_a / int_b)
print('5. 몫 :',int_a // int_b)
print('6. 나머지 :',int_a % int_b)
